project_id                              = "r-server-326920"
region                                  = "europe-west4"
zone                                    = "europe-west4"
service_account                         = "terraform@r-server-326920.iam.gserviceaccount.com"
artifact_repository_name               = "deploy-ml-model"